###consul服务端口号
server:
  port: 80

spring:
  application:
    name: springcloud-consumer-order
  ####consul注册中心地址
  cloud:
    consul:
      host: localhost
      discovery:
        port: 8500
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}
